modLoader="javafml"
loaderVersion="[46,)"
issueTrackerURL="https://github.com/Quizer9O8/Strata/issues"
license="MIT"

[[mods]]
modId="strata"
version="1.3.1"
displayName="Strata"
# updateJSONURL="http://myurl.me/"
displayURL="https://github.com/Quizer9O8/Strata"
logoFile="strata.png"
credits="Quizer9O8,Gaming_Crew"
authors="Quizer9O8"
description='''Strata is a mod that adds various types of rocks into the game. It changes the look and feel of the game and gives you a plethora of blocks to interact with.'''

[[dependencies.examplemod]]
    modId="forge"
    mandatory=true
    versionRange="[46,)"
    # An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
    ordering="NONE"
    # Side this dependency is applied on - BOTH, CLIENT or SERVER
    side="BOTH"

[[dependencies.examplemod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"
